# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v -c release
    - uses: actions/upload-artifact@v3
      with:
        name: bel
        path: bel
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: bel
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
